// apps/frontend/src/routes/_auth/login.tsx
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { PasswordInput } from "@/components/ui/password-input"
import { login } from "@/lib/api"
import { save } from "@/lib/auth"

export const Route = createFileRoute("/_auth/login")({
	component: LoginPage,
})

function LoginPage() {
	const navigate = useNavigate()
	const [email, setEmail] = useState("")
	const [password, setPassword] = useState("")
	const [error, setError] = useState("")
	const [loading, setLoading] = useState(false)

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault()
		setError("")
		setLoading(true)
		try {
			const res = await login(email, password)
			save(res.accessToken, res.refreshToken, res.user)
			const dest = res.user.role === "admin" ? "/admin" : "/dashboard"
			navigate({ to: dest })
		} catch (err) {
			setError(err instanceof Error ? err.message : "Đăng nhập thất bại")
		} finally {
			setLoading(false)
		}
	}

	return (
		<div className="space-y-6">
			<div>
				<h2 className="text-2xl font-semibold tracking-tight">Đăng nhập</h2>
				<p className="mt-1 text-sm text-muted-foreground">Nhập email và mật khẩu để tiếp tục</p>
			</div>
			<form onSubmit={handleSubmit} className="space-y-4">
				<div className="space-y-2">
					<Label htmlFor="email">Email</Label>
					<Input
						id="email"
						type="email"
						placeholder="you@example.com"
						value={email}
						onChange={(e) => setEmail(e.target.value)}
						required
					/>
				</div>
				<div className="space-y-2">
					<Label htmlFor="password">Mật khẩu</Label>
					<PasswordInput
						id="password"
						placeholder="••••••••"
						value={password}
						onChange={(e) => setPassword(e.target.value)}
						required
					/>
				</div>
				{error && <p className="text-sm text-destructive">{error}</p>}
				<Button type="submit" className="w-full" disabled={loading}>
					{loading ? "Đang đăng nhập..." : "Đăng nhập"}
				</Button>
			</form>
			<p className="text-center text-sm text-muted-foreground">
				Chưa có tài khoản?{" "}
				<Link to="/register" className="text-primary hover:underline">
					Đăng ký
				</Link>
			</p>
		</div>
	)
}

// apps/admin/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { auth } from '$lib/auth.svelte';

	let email = $state('');
	let password = $state('');
	let error = $state('');
	let loading = $state(false);

	async function login() {
		error = '';
		loading = true;
		try {
			const res = await api<{ data: { access_token: string; user: { id: string; email: string; full_name: string; role: string } } }>(
				'/api/v1/auth/login',
				{ method: 'POST', body: JSON.stringify({ email, password }) }
			);
			const { access_token, user } = res.data;
			if (user.role !== 'admin' && user.role !== 'staff') {
				error = 'Access denied. Admin or staff only.';
				return;
			}
			auth.set(access_token, user);
			goto('/');
		} catch (e) {
			error = e instanceof Error ? e.message : 'Login failed';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-(--color-background)">
	<div class="card w-full max-w-sm p-8 space-y-6">
		<div>
			<h1 class="text-xl font-semibold text-(--color-foreground)">VSTEP Admin</h1>
			<p class="text-sm text-(--color-muted) mt-1">Sign in to continue</p>
		</div>

		<form onsubmit={(e) => { e.preventDefault(); login(); }} class="space-y-4">
			<div class="space-y-1">
				<label class="text-xs font-medium text-(--color-muted)" for="email">Email</label>
				<input id="email" type="email" class="input" bind:value={email} required autocomplete="email" />
			</div>
			<div class="space-y-1">
				<label class="text-xs font-medium text-(--color-muted)" for="password">Password</label>
				<input id="password" type="password" class="input" bind:value={password} required autocomplete="current-password" />
			</div>

			{#if error}
				<p class="text-xs text-(--color-destructive)">{error}</p>
			{/if}

			<button type="submit" class="btn btn-primary w-full justify-center" disabled={loading}>
				{loading ? 'Signing in…' : 'Sign in'}
			</button>
		</form>
	</div>
</div>
