// apps/admin/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { auth } from '$lib/auth.svelte';

	let email = $state('');
	let password = $state('');
	let error = $state('');
	let loading = $state(false);

	async function login() {
		error = '';
		loading = true;
		try {
			const res = await api<{ data: { access_token: string; user: { id: string; email: string; full_name: string; role: string } } }>(
				'/api/v1/auth/login',
				{ method: 'POST', body: JSON.stringify({ email, password }) }
			);
			const { access_token, user } = res.data;
			if (user.role !== 'admin' && user.role !== 'staff') {
				error = 'Access denied. Admin or staff only.';
				return;
			}
			auth.set(access_token, user);
			goto('/');
		} catch (e) {
			error = e instanceof Error ? e.message : 'Login failed';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-(--color-background)">
	<div class="card w-full max-w-sm p-8 space-y-6">
		<div>
			<h1 class="text-xl font-semibold text-(--color-foreground)">VSTEP Admin</h1>
			<p class="text-sm text-(--color-muted) mt-1">Sign in to continue</p>
		</div>

		<form onsubmit={(e) => { e.preventDefault(); login(); }} class="space-y-4">
			<div class="space-y-1">
				<label class="text-xs font-medium text-(--color-muted)" for="email">Email</label>
				<input id="email" type="email" class="input" bind:value={email} required autocomplete="email" />
			</div>
			<div class="space-y-1">
				<label class="text-xs font-medium text-(--color-muted)" for="password">Password</label>
				<input id="password" type="password" class="input" bind:value={password} required autocomplete="current-password" />
			</div>

			{#if error}
				<p class="text-xs text-(--color-destructive)">{error}</p>
			{/if}

			<button type="submit" class="btn btn-primary w-full justify-center" disabled={loading}>
				{loading ? 'Signing in…' : 'Sign in'}
			</button>
		</form>
	</div>
</div>

// apps/admin/src/routes/login.tsx
import { useMutation } from "@tanstack/react-query"
import { createFileRoute, redirect } from "@tanstack/react-router"
import { useState } from "react"
import { Button } from "#/components/Button"
import { Input } from "#/components/Input"
import { type ApiResponse, api, extractError } from "#/lib/api"
import { useAuth } from "#/lib/auth"

interface LoginResponse {
	access_token: string
	user: {
		id: string
		email: string
		full_name: string
		role: AdminRole
	}
}

export const Route = createFileRoute("/login")({
	beforeLoad: () => {
		const { token, user } = useAuth.getState()
		if (token && user) throw redirect({ to: "/" })
	},
	component: LoginPage,
})

function LoginPage() {
	const setSession = useAuth((s) => s.setSession)
	const [email, setEmail] = useState("")
	const [password, setPassword] = useState("")
	const [error, setError] = useState<string | null>(null)

	const mutation = useMutation({
		mutationFn: async () => {
			const res = await api
				.post("auth/login", { json: { email, password } })
				.json<ApiResponse<LoginResponse>>()
			return res.data
		},
		onSuccess: (data) => {
			const user = data.user
			if (!["admin", "staff", "teacher"].includes(user.role)) {
				setError("Tài khoản không có quyền truy cập admin panel.")
				return
			}
			setSession(data.access_token, {
				id: user.id,
				email: user.email,
				name: user.full_name,
				role: user.role,
			})
			window.location.href = "/"
		},
		onError: (err) => {
			const { message } = extractError(err)
			setError(message || "Đăng nhập thất bại")
		},
	})

	return (
		<div className="flex min-h-screen items-center justify-center bg-background px-4">
			<form
				onSubmit={(e) => {
					e.preventDefault()
					setError(null)
					mutation.mutate()
				}}
				className="w-full max-w-sm rounded-(--radius-card) border border-border bg-surface p-6 shadow-sm"
			>
				<div className="mb-5">
					<h1 className="text-lg font-semibold tracking-tight">VSTEP Admin</h1>
					<p className="mt-1 text-sm text-muted">Đăng nhập để tiếp tục.</p>
				</div>
				<div className="flex flex-col gap-3">
					<div className="flex flex-col gap-1.5">
						<label htmlFor="email" className="text-xs font-medium text-muted">
							Email
						</label>
						<Input
							id="email"
							type="email"
							required
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							autoComplete="email"
						/>
					</div>
					<div className="flex flex-col gap-1.5">
						<label htmlFor="password" className="text-xs font-medium text-muted">
							Mật khẩu
						</label>
						<Input
							id="password"
							type="password"
							required
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							autoComplete="current-password"
						/>
					</div>
					{error && <div className="rounded-md bg-danger-tint px-3 py-2 text-xs text-danger">{error}</div>}
					<Button type="submit" size="lg" loading={mutation.isPending}>
						Đăng nhập
					</Button>
				</div>
			</form>
		</div>
	)
}
